# -*- coding: utf-8 -*-
"""TIC_TAC_TOE.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-Fut1PyrVVndMgq9XI79C3nYI4sw1SRe
"""

def play_tic_tac_toe():
    board = [' '] * 9
    player = 'X'
    wins = [(0,1,2), (3,4,5), (6,7,8), (0,3,6), (1,4,7), (2,5,8), (0,4,8), (2,4,6)]

    def show():
        for i in range(0, 9, 3):
            print(' | '.join(board[i:i+3]))
            if i < 6: print('---------')

    show()
    for turn in range(9):
        while True:
       try:
                move = int(input(f"Player {player}, enter position (1-9): ")) - 1
                if 0 <= move <= 8 and board[move] == ' ':
                    board[move] = player
                    break
                print("Invalid move. Try again.")
            except ValueError:
                print("Please enter a number from 1 to 9.")

        show()
        if any(all(board[pos] == player for pos in combo) for combo in wins):
            opponent = 'O' if player == 'X' else 'X'
            print(f"\nGame Over! Player {player} WINS! Player {opponent} LOSES!")
            return
        player = 'O' if player == 'X' else 'X'

    print("\nGame Over! It's a DRAW! No one wins or loses.")

play_tic_tac_toe()