# -*- coding: utf-8 -*-
"""vacccume_cleaner.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1huLhuQY1SCxDqe8k8z3HRXJ3nGCgVF1y
"""

class Room:
    def __init__(self, name, is_dirty=True):
        self.name = name
        self.is_dirty = is_dirty

    def get_state(self):
        return 'dirty' if self.is_dirty else 'clean'

    def clean(self):
        if self.is_dirty:
            print(f"  Cleaning {self.name}...")
            self.is_dirty = False
        else:
            print(f"  {self.name} is already clean.")

    def __str__(self):
        return f"Room {self.name} (State: {self.get_state()})"


class VacuumCleanerAgent:
    def __init__(self, rooms):
        self.rooms = rooms  # Dictionary of Room objects {name: Room_object}
        self.current_room_index = 0
        self.num_rooms = len(rooms)
        self.room_names = list(rooms.keys())

    def perceive(self):
        if not self.rooms:
            return None
        current_room_name = self.room_names[self.current_room_index]
        return self.rooms[current_room_name].get_state()

    def decide_action(self, percept):
        if percept == 'dirty':
            return 'clean'
        return 'move_to_next'

    def execute_action(self, action):
        if not self.rooms:
            print("No rooms to operate in.")
            return

        current_room_name = self.room_names[self.current_room_index]
        current_room = self.rooms[current_room_name]

        if action == 'clean':
            print(f"Agent in {current_room.name}: Perceived as dirty. Action: Cleaning.")
            current_room.clean()
        elif action == 'move_to_next':
            print(f"Agent in {current_room.name}: Perceived as clean. Action: Moving to next room.")
        else:
            print(f"Agent in {current_room.name}: Unknown action '{action}'.")

        # Move to the next room
        self.current_room_index = (self.current_room_index + 1) % self.num_rooms

    def run(self):
        print("\n--- Starting Vacuum Cleaner Agent Simulation ---")


        rooms_to_visit = list(self.room_names) # Keep track of rooms to visit
        visited_count = 0

        while rooms_to_visit:
            if visited_count >= self.num_rooms * 2: # Prevent infinite loop if logic fails
                print("Reached maximum visit iterations, stopping.")
                break

            current_room_name = self.room_names[self.current_room_index]
            current_room = self.rooms[current_room_name]
            print(f"\nAgent is currently in {current_room.name}.")

            percept = self.perceive()
            action = self.decide_action(percept)
            self.execute_action(action)

            if current_room.get_state() == 'clean' and current_room_name in rooms_to_visit:
                rooms_to_visit.remove(current_room_name)
            visited_count += 1
            if all(room.get_state() == 'clean' for room in self.rooms.values()):
                print("All rooms are clean. Agent stopping.")
                break

        print("\n--- Simulation Ended ---")




print("Let's set up the rooms for the vacuum cleaner agent.")

num_rooms = 0
while num_rooms <= 0:
    try:
        num_rooms = int(input("Enter the number of rooms: "))
        if num_rooms <= 0:
            print("Please enter a positive number for rooms.")
    except ValueError:
        print("Invalid input. Please enter a number.")

initial_rooms = {}
for i in range(num_rooms):
    room_name = input(f"Enter name for Room {i+1} (e.g., 'A', 'Bedroom'): ")
    while True:
        state_input = input(f"Is {room_name} dirty or clean? (type 'dirty' or 'clean'): ").lower().strip()
        if state_input in ['dirty', 'clean']:
            is_dirty = (state_input == 'dirty')
            initial_rooms[room_name] = Room(room_name, is_dirty)
            break
        else:
            print("Invalid input. Please type 'dirty' or 'clean'.")

print("\nInitial Room States:")
for room in initial_rooms.values():
    print(f"- {room}")

agent = VacuumCleanerAgent(initial_rooms)




agent.run()

print("\nFinal Room States:")
for room in initial_rooms.values():
    print(f"- {room}")